---
- name: Get VLANs and debug list
  hosts: dnac
  connection: local
  gather_facts: False
  vars_files:
    - creds.yml

  tasks:
    - name: Login to DNAC
      uri:
        url: https://dcloud-dna-center-inst-sjc.cisco.com/dna/system/api/v1/auth/token
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          'content-type': 'application/json'
      register: token
    - name: Assign device to site
      uri:
        url: https://dcloud-dna-center-inst-sjc.cisco.com/dna/intent/api/v1/onboarding/pnp-device/site-claim
        method: POST
        body_format: json
        body:
          {
        "deviceId": "JPG2227023C",
        "siteId": "Global/North America/USA/California/San Jose/SJC01",
        "type": "C9200"
          }
        headers:
          'content-type': 'application/json'
          'x-auth-header': "{{ token.json.Token }}"
