---
- name: include creds
<<<<<<< HEAD
=======
  hosts: aci
>>>>>>> 867584ec257e56f414907febc44c0cb39e20718e
  gather_facts: false
  vars_files:
    creds.yml

<<<<<<< HEAD
- name: create ACI tenant
  hosts: apic
  gather_facts: false
  connection: local
=======
>>>>>>> 867584ec257e56f414907febc44c0cb39e20718e
  tasks:
  - name: Add a new bridge domain
    aci_bd:
      host: aci
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: DC2
      bd: DC2-BD
      vrf: DC2-VRF
      description: Demo BD
      state: present
      validate_certs: no
  - name: Add subnets to BD
    aci_bd:
      host: aci
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: DC2
      bd: DC2-BD
      gateway: 192.2.200.254
      mask: 24
      state: present
      validate_certs: no
