---
<<<<<<< HEAD
- hosts: apic
=======
- name: Create ACI Constructs
- hosts: aci
>>>>>>> 867584ec257e56f414907febc44c0cb39e20718e
- gather_facts: no
- import_playbook: tenant.yml
- import_playbook: vrf.yml
- import_playbook: bd.yml
