---
- name: include creds
  hosts: dnac
  gather_facts: false
  vars_files:
    dnac_creds.yml

  tasks:

  - name: Add a new tenant
    aci_tenant:
      host: aci
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: DC2
      description: Production tenant
      state: present
      validate_certs: no
