---
- name: include creds
  hosts: dnac
  connection: local
  gather_facts: false
  vars_files:
    dnac_creds.yml

  tasks:

  - name: Add a new tenant
    uri:
      user: "{{ username }}"
      password: "{{ password }}"
      method: GET
      url: https://sandboxdnac2.cisco.com/dna/intent/api/v1/business/ssid
