---
- name: include creds
  hosts: dnac
  gather_facts: false
  vars_files:
    dnac_creds.yml

  tasks:

  - name: Add a new tenant
    uri:
	    url: https://dcloud-dna-center-inst-sjc.cisco.com/dna/intent/api/v1/enterprise-ssid?ssidName=<ssidName>
	    method: GET
	    headers: 
