---
- name: create ACI tenant
  hosts: apic
  gather_facts: no
  connection: local
  tasks:
  - name: Add a new tenant
    aci_tenant:
      host: {{ apic }}
      username: {{ username }}
      password: {{ password }}
      tenant: DC2
      description: Production tenant
      state: present
      validate_certs: no
