---
- name: include creds
  hosts: aci
  gather_facts: false
  vars_files:
    creds.yml

  tasks:

  - name: Add a new tenant
    aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: DC2
      description: Production tenant
      state: present
      validate_certs: no
