---
- name: include creds
  hosts: apic
  connection: local
  gather_facts: false
  vars_files:
    creds.yml

  tasks:
  - name: login to fabric
    uri:
      method: POST
      body_format: json
      url: https://sandboxapicdc.cisco.com/api/aaaLogin.json
      body: "{
      'aaaUser': {
              'attributes': {
                  'name': 'admin',
                  'pwd': 'ciscopsdt'
              }
          }
      }"
      validate_certs: no
  - name: Add a new tenant
    uri:
      method: POST
      body_format: json
      url: https://sandboxapicdc.cisco.com/api/node/mo/uni/tn-ISEisBAD.json
      body: "{'fvTenant':{'attributes':{'dn':'uni/tn-ISEisBAD','name':'ISEisBAD','rn':'tn-ISEisBAD','status':'created'},'children':[]}}"
      body_format: json
      validate_certs: no
