---
- name: include creds
  hosts: aci
  gather_facts: no
  vars_files:
    creds.yml

  tasks:
  - name: Add a new tenant
    aci_vrf:
      host: aci
      username: "{{ username }}"
      password: "{{ password }}"
      vrf: DC2-VRF
      tenant: DC2
      description: VRF for demo
      policy_control_direction: ingress
      policy_control_preference: enforced
      state: present
      validate_certs: no
